// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcegQIEr0gyg4AaiGcc-cmqKFih1skPjo',
    appId: '1:1074625929550:web:7d9615e39158280c757e1f',
    messagingSenderId: '1074625929550',
    projectId: 'creche-66529',
    authDomain: 'creche-66529.firebaseapp.com',
    databaseURL: 'https://creche-66529-default-rtdb.firebaseio.com',
    storageBucket: 'creche-66529.firebasestorage.app',
    measurementId: 'G-PZJZTGYZ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUREdAFpQN4XyEY4ghbrxY9erLtnOCOn4',
    appId: '1:1074625929550:android:b7739929f2c76cdd757e1f',
    messagingSenderId: '1074625929550',
    projectId: 'creche-66529',
    databaseURL: 'https://creche-66529-default-rtdb.firebaseio.com',
    storageBucket: 'creche-66529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUCb_dFblE0Xfi14ceAaZaywfffyTqw4Y',
    appId: '1:1074625929550:ios:c4c128f2501eab2b757e1f',
    messagingSenderId: '1074625929550',
    projectId: 'creche-66529',
    databaseURL: 'https://creche-66529-default-rtdb.firebaseio.com',
    storageBucket: 'creche-66529.firebasestorage.app',
    iosClientId: '1074625929550-c00lqf0h458frddg0b504bqgdhao1j4k.apps.googleusercontent.com',
    iosBundleId: 'com.connacri.creche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUCb_dFblE0Xfi14ceAaZaywfffyTqw4Y',
    appId: '1:1074625929550:ios:c4c128f2501eab2b757e1f',
    messagingSenderId: '1074625929550',
    projectId: 'creche-66529',
    databaseURL: 'https://creche-66529-default-rtdb.firebaseio.com',
    storageBucket: 'creche-66529.firebasestorage.app',
    iosClientId: '1074625929550-c00lqf0h458frddg0b504bqgdhao1j4k.apps.googleusercontent.com',
    iosBundleId: 'com.connacri.creche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcegQIEr0gyg4AaiGcc-cmqKFih1skPjo',
    appId: '1:1074625929550:web:86831e657378b20a757e1f',
    messagingSenderId: '1074625929550',
    projectId: 'creche-66529',
    authDomain: 'creche-66529.firebaseapp.com',
    databaseURL: 'https://creche-66529-default-rtdb.firebaseio.com',
    storageBucket: 'creche-66529.firebasestorage.app',
    measurementId: 'G-VKH9FS2NTD',
  );

}